### ISSUE TITLE
Padding between Header and Side Bar/Tab Editor

### ISSUE THREAD

**Issue by timcrisp94** [RyanSUP/riffin-v2#114]
80px of top-padding had us miffed yesterday as we were finishing.

Identified style property on line 117 in Home. 

Even though it's a property we added ourselves, helpful article for over-riding style properties:
https://mui.com/material-ui/react-box/

**Comment by RyanSUP** [comment]
Thanks for the research @timcrisp94! Turns out the 'whitespace' css setting that Dave put in for the Notes component was somehow effecting this margin. 🤷‍♂️

I took the whitespace out of the global stylesheet and it fixed the issue. I moved Daves' CSS updates locally to the component.
