### ISSUE TITLE
Protect tablature Edit / delete routes

### ISSUE THREAD

**Issue by RyanSUP** [RyanSUP/riffin-v2#29]
### Desired behavior  
Only the user that owns the tablature should be able to edit and delete it

### Current behavior
Any user can update / delete any tab. If the tabID is known, a user can manually navigate to /edit/{tabID} to access the edit/delete routes, or use postman to send a data payload.

### Steps to fix
We should protect the routes on the frontend and the backend

**Comment by timcrisp94** [comment]
Utilize AWS Cognito features to ensure a user can not make an an using an email address that’s already been used.
-Delete getTablatureById from tablature services

deleteTab:
—add todo: add cognito username to payload
—add user.username to delete tab button function parameters
—in createTablatureHandler function, add if user != owner condtion and .then(return)

Update config variables again, prefix/stack name, bucket, redeploy to production

Move cognitoUser info to createTab

Delete function updated. Delete routes protected. 

Update functions:
—add username to updateButton
—frontend: add payload to update in tablatureServices
—add TablatureModel to updateTablature Handler
—update conditionals in updateTablatureHandler
	—if not user, else save()
	—adding body to JSON to handle “end of input” errors
