### ISSUE TITLE
The selected nav button text doesn't align with the rest of the buttons

### ISSUE THREAD

**Issue by RyanSUP** [RyanSUP/riffin-v2#52]
For some reason it gets shifted to the right. Text should be justified left. The buttons (CollectionButton, CreateBassTabButton, CreateGuitarTabButton) have a "justify: left" property but maybe it needs to be a text align or something?

<img width="189" alt="Screen Shot 2022-09-26 at 10 36 19 AM" src="https://user-images.githubusercontent.com/6211733/192305509-aa96b7b1-d3ab-4e60-a806-9a0d2479b6a3.png">

**Comment by RyanSUP** [comment]
I played around with the inspector tool and there is more padding added to the selected button, maybe because it's a different MUI button type? Might have to explicitly define padding on the button styles.

**Comment by dcollis92** [comment]
on it cap'n
