### ISSUE TITLE
Deploy Riffin with multiple environments

### ISSUE THREAD

**Issue by RyanSUP** [RyanSUP/riffin-v2#71]
Currently we are working on 1 development branch, which is bad practice. We'll need at least 2: Development and Production.

This will require setting up multiple branches on AWS Gateway with different environment variables.

**Comment by RyanSUP** [comment]
3 branches
- dev
-QA
- prod

Each branch needs:
mongo-db cluster
api gateway link
cognito userpool

**Comment by RyanSUP** [comment]
Look into these variables

REACT_APP_COGNITO_USER_POOL_ID
REACT_APP_COGNITO_CLIENT_ID
REACT_APP_STACK_URL

**Comment by timcrisp94** [comment]
Week of  11/14: successfully moved backend to production branch. Changes made to dev branch integrating backend, plus changes on main to be merged.
