### ISSUE TITLE
Provide demo tab to new / non users

### ISSUE THREAD

**Issue by RyanSUP** [RyanSUP/riffin-v2#74]
Create a demo tab (must be original as to avoid copyright issues).
Non users should be able to edit the demo tab.
New users should have the demo tab in their profile.

Demo tab should illustrate:
- different size blocks
- Blocks with notes
- blocks without notes
- using tags

**Comment by timcrisp94** [comment]
Demo Tab created 11/17 - still could use some flair on the blocks.
